### ISSUE TITLE
Force cache hit upon dependency change

### ISSUE THREAD

**Issue by Drenth1** [B2C6-G1/interface#9]
### Issue

GitHub actions cache's zijn geldig voor 7 dagen. Wanneer de dependencies binnen deze 7 dagen veranderen, staan de nieuwe dependencies niet in de cache. Hierdoor zal de testfase falen wanneer er testen zijn die afhankelijk zijn van die nieuwe dependencies.

De cache action heeft geen ingebouwde manier om het aanmaken van een nieuwe cache te forceren. Hierdoor zou je in principe 7 dagen moeten wachten voordat de cache wordt bijgewerkt met de recentere dependencies. Echter, het is mogelijk om het aanmaken van een nieuwe cache te forceren door de naam van de cache key te veranderen.

### Mogelijke oplossing 

Door een secret aan te maken in de GitHub repository en deze `CACHE_VERSION` te noemen en hier een getal aan toe te kennen, kan het aanmaken van een nieuwe cache geforceerd worden door dit versienummer aan te passen. Hiervoor is in iedere workflow, bij iedere cache actie een aanpassing van de key nodig:

```yml
- name: Cache npm dependencies
   uses: actions/cache@v2
   with:
       path: node_modules
       key: ${{ runner.os }}-${{ env.GITHUB_RUN_NUMBER }}-npm-prod-${ secrets.CACHE_VERSION }
```
